import { Link, Outlet, useNavigate, useRouterState } from "@tanstack/react-router";
import { CreditCard, FileClock, LayoutDashboard, LogOut, Menu, Settings, Shapes, Sparkles, X } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Brand } from "./brand";
import { supabase } from "@/integrations/supabase/client";
import { useQueryClient } from "@tanstack/react-query";
const nav=[{to:"/dashboard",label:"Overview",icon:LayoutDashboard},{to:"/templates/manage",label:"Templates",icon:Shapes},{to:"/generate",label:"Generate",icon:Sparkles},{to:"/history",label:"History",icon:FileClock},{to:"/billing",label:"Billing",icon:CreditCard},{to:"/settings",label:"Settings",icon:Settings}] as const;
export function WorkspaceShell(){const [open,setOpen]=useState(false);const path=useRouterState({select:s=>s.location.pathname});const navigate=useNavigate();const qc=useQueryClient();async function signOut(){await qc.cancelQueries();qc.clear();await supabase.auth.signOut();navigate({to:"/auth",replace:true});}return <div className="min-h-screen bg-background text-foreground"><header className="sticky top-0 z-40 flex h-16 items-center justify-between border-b border-border bg-background/90 px-4 backdrop-blur md:hidden"><Brand/><Button variant="ghost" size="icon" aria-label="Toggle navigation" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</Button></header><aside className={`${open?"flex":"hidden"} fixed inset-y-0 left-0 z-30 w-64 flex-col border-r border-border bg-surface p-5 md:flex`}><Brand/><div className="mt-10 font-mono text-[10px] uppercase text-muted-foreground">Core operations</div><nav className="mt-3 space-y-1">{nav.map(item=>{const Icon=item.icon;const active=path===item.to;return <Link key={item.to} to={item.to} onClick={()=>setOpen(false)} className={`flex items-center gap-3 rounded-md border px-3 py-2.5 text-sm font-semibold transition ${active?"border-primary/30 bg-primary/10 text-foreground":"border-transparent text-muted-foreground hover:bg-accent hover:text-foreground"}`}><Icon className={active?"text-primary":""}/>{item.label}</Link>})}</nav><div className="mt-auto rounded-md border border-primary/20 bg-primary/5 p-4"><p className="text-xs font-semibold text-primary">Starter capacity</p><div className="mt-3 h-1 overflow-hidden rounded-full bg-muted"><div className="h-full w-[18%] bg-primary"/></div><p className="mt-2 font-mono text-[10px] text-muted-foreground">18 / 100 this month</p></div><Button variant="ghost" className="mt-3 justify-start text-muted-foreground" onClick={signOut}><LogOut/> Sign out</Button></aside>{open&&<button aria-label="Close navigation" className="fixed inset-0 z-20 bg-background/70 md:hidden" onClick={()=>setOpen(false)}/>}<main className="min-h-screen md:pl-64"><Outlet/></main></div>}
